MAX_REPUTAION_COMPLETED = "Max"
REPUTATION_GAINED_MESSAGE = "Reputaion with %s is %s%% to %s!"
MAX_REPUTAION_MESSAGE = "You are max reutation status with %s!"
REP_CHECK = "RepCheck"
COMPLETED_BLOCK_CHAR = "█"
UNCOMPLETED_BLOCK_CHAR = "░"
GREEN ="|cff00ff00"
RED = "|cffff0000"